{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-s3bucket-exporter.secretName" . }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-s3bucket-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  s3AccessKey: {{ required "A valid .Values.s3bucket.s3AccessKey entry required!" .Values.s3bucket.s3AccessKey | b64enc }}
  s3SecretKey: {{ required "A valid .Values.s3bucket.s3SecretKey entry required!" .Values.s3bucket.s3SecretKey | b64enc }}
{{- end }}